export const SET_SELECTED_APPLICATION = "SET_SELECTED_APPLICATION";
export const CHANGE_APPLICATION = "CHANGE_APPLICATION";

export const FETCH_APPLICATION_REQUEST = "FETCH_APPLICATION_REQUEST";
export const FETCH_APPLICATION_SUCCESS = "FETCH_APPLICATION_SUCCESS";
export const FETCH_APPLICATION_FAILURE = "FETCH_APPLICATION_FAILURE";
