export const SET_POINT1 = "SET_POINT1";
export const SET_POINT2 = "SET_POINT2";
export const FETCH_POINTS_REQUEST = "FETCH_POINTS_REQUEST";
export const FETCH_POINTS_SUCCESS = "FETCH_POINTS_SUCCESS";
export const FETCH_POINTS_FAILURE = "FETCH_POINTS_FAILURE";
